name: Generate Snake Game Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch: 

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake Game SVG
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit and push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add github-contribution-grid-snake.svg github-contribution-grid-snake-dark.svg
          git commit -m "Update Snake Game SVG"
          git push
